import axios from 'axios';

const API_BASE = '/api';

export const productosService = {
  /**
   * Obtener todos los productos (simula API)
   */
  async obtenerProductos() {
    try {
      // Simulación de respuesta API - cuando tengas backend real, cambiar esto:
      // const response = await axios.get(`${API_BASE}/productos`);
      // return response.data;

      return new Promise((resolve) => {
        setTimeout(() => {
          resolve({
            data: [
              {
                producto_id: 1,
                producto_uuid: '8b4d3a8b-1d4f-4b5a-9e84-7c0ddf0e0a11',
                sku: 'SKU-1001',
                upc: '7501234567890',
                nombre: 'Paracetamol 500 mg',
                descripcion: 'Tabletas para alivio del dolor y fiebre.',
                unidad_medida_id: 2,
                categoria_id: 1,
                categoria_nombre: 'Analgésicos',
                status: 'Activo',
                con_lote: true,
                url_imagen: '',
                con_impuestos: true,
                precio_publico: '45.00',
                volumen_unidad: 'ml',
                volumen_valor: 0,
                peso_unidad: 'mg',
                peso_valor: 500,
                unidad_entrada: 'Caja',
                unidad_salida: 'Tableta',
                control_almacen: true,
                factor_unidades: 10,
                costo_compra: '32.10',
                numero_registro_sanitario: 'RS-2026-001',
                temperatura: 'Ambiente',
                presentacion: 'Caja con 10 tabletas',
                fecha_entrada: '2026-06-20',
                tags: 'fiebre, dolor, gripe',
                objeto_impuesto_id: 1,
                tasa_cuota_id: 1,
                clave_prod_serv_id: '51191500',
                usuario_creacion: 'Sistema',
                usuario_actualizacion: 'Sistema',
                fecha_creacion: '2026-06-20 10:15',
                fecha_actualizacion: '2026-06-20 10:15',
              },
              {
                producto_id: 2,
                producto_uuid: 'd3f5c4a4-2c57-4d98-936c-5ad8b9c6a222',
                sku: 'SKU-1002',
                upc: '7501234567891',
                nombre: 'Ibuprofeno 400 mg',
                descripcion: 'Antiinflamatorio de uso frecuente.',
                unidad_medida_id: 2,
                categoria_id: 1,
                categoria_nombre: 'Antiinflamatorios',
                status: 'Activo',
                con_lote: true,
                url_imagen: '',
                con_impuestos: true,
                precio_publico: '52.00',
                volumen_unidad: 'ml',
                volumen_valor: 0,
                peso_unidad: 'mg',
                peso_valor: 400,
                unidad_entrada: 'Caja',
                unidad_salida: 'Tableta',
                control_almacen: true,
                factor_unidades: 10,
                costo_compra: '36.20',
                numero_registro_sanitario: 'RS-2026-002',
                temperatura: 'Ambiente',
                presentacion: 'Caja con 10 tabletas',
                fecha_entrada: '2026-06-20',
                tags: 'dolor, inflamación',
                objeto_impuesto_id: 1,
                tasa_cuota_id: 1,
                clave_prod_serv_id: '51191501',
                usuario_creacion: 'Sistema',
                usuario_actualizacion: 'Sistema',
                fecha_creacion: '2026-06-20 11:00',
                fecha_actualizacion: '2026-06-20 11:00',
              },
              {
                producto_id: 3,
                producto_uuid: 'b7cb2a72-5d3a-4a8f-8b1d-4f5d4d1b0333',
                sku: 'SKU-1003',
                upc: '7501234567892',
                nombre: 'Loratadina 10 mg',
                descripcion: 'Antihistamínico para síntomas alérgicos.',
                unidad_medida_id: 2,
                categoria_id: 2,
                categoria_nombre: 'Antialérgicos',
                status: 'Activo',
                con_lote: true,
                url_imagen: '',
                con_impuestos: true,
                precio_publico: '39.00',
                volumen_unidad: 'ml',
                volumen_valor: 0,
                peso_unidad: 'mg',
                peso_valor: 10,
                unidad_entrada: 'Caja',
                unidad_salida: 'Tableta',
                control_almacen: true,
                factor_unidades: 10,
                costo_compra: '24.90',
                numero_registro_sanitario: 'RS-2026-003',
                temperatura: 'Ambiente',
                presentacion: 'Caja con 10 tabletas',
                fecha_entrada: '2026-06-20',
                tags: 'alergia, congestión',
                objeto_impuesto_id: 1,
                tasa_cuota_id: 1,
                clave_prod_serv_id: '51191502',
                usuario_creacion: 'Sistema',
                usuario_actualizacion: 'Sistema',
                fecha_creacion: '2026-06-20 12:10',
                fecha_actualizacion: '2026-06-20 12:10',
              },
              {
                producto_id: 4,
                producto_uuid: '6f8f8f0f-8c77-4c6f-a123-1d8c9ef70444',
                sku: 'SKU-1004',
                upc: '7501234567893',
                nombre: 'Suero oral',
                descripcion: 'Solución de rehidratación oral.',
                unidad_medida_id: 3,
                categoria_id: 3,
                categoria_nombre: 'Rehidratación',
                status: 'Activo',
                con_lote: false,
                url_imagen: '',
                con_impuestos: true,
                precio_publico: '28.50',
                volumen_unidad: 'ml',
                volumen_valor: 500,
                peso_unidad: 'g',
                peso_valor: 0,
                unidad_entrada: 'Pieza',
                unidad_salida: 'Pieza',
                control_almacen: true,
                factor_unidades: 1,
                costo_compra: '18.70',
                numero_registro_sanitario: 'RS-2026-004',
                temperatura: 'Ambiente',
                presentacion: 'Botella 500 ml',
                fecha_entrada: '2026-06-20',
                tags: 'deshidratación, diarrea',
                objeto_impuesto_id: 1,
                tasa_cuota_id: 1,
                clave_prod_serv_id: '51191600',
                usuario_creacion: 'Sistema',
                usuario_actualizacion: 'Sistema',
                fecha_creacion: '2026-06-20 12:50',
                fecha_actualizacion: '2026-06-20 12:50',
              },
              {
                producto_id: 5,
                producto_uuid: 'aa12bb34-cc56-4dd7-9e01-ffeeddcc5555',
                sku: 'SKU-1005',
                upc: '7501234567894',
                nombre: 'Gasas estériles',
                descripcion: 'Material de curación estéril.',
                unidad_medida_id: 4,
                categoria_id: 4,
                categoria_nombre: 'Curación',
                status: 'Activo',
                con_lote: false,
                url_imagen: '',
                con_impuestos: true,
                precio_publico: '15.00',
                volumen_unidad: '',
                volumen_valor: 0,
                peso_unidad: '',
                peso_valor: 0,
                unidad_entrada: 'Paquete',
                unidad_salida: 'Paquete',
                control_almacen: true,
                factor_unidades: 1,
                costo_compra: '9.30',
                numero_registro_sanitario: 'RS-2026-005',
                temperatura: 'Ambiente',
                presentacion: 'Paquete con 10 piezas',
                fecha_entrada: '2026-06-20',
                tags: 'curación, herida',
                objeto_impuesto_id: 1,
                tasa_cuota_id: 1,
                clave_prod_serv_id: '42131700',
                usuario_creacion: 'Sistema',
                usuario_actualizacion: 'Sistema',
                fecha_creacion: '2026-06-20 13:20',
                fecha_actualizacion: '2026-06-20 13:20',
              },
              {
                producto_id: 6,
                producto_uuid: 'bb22cc33-dd44-4ee5-9f11-aabbccdd6666',
                sku: 'SKU-1006',
                upc: '7501234567895',
                nombre: 'Vitamina C',
                descripcion: 'Suplemento vitamínico de apoyo general.',
                unidad_medida_id: 2,
                categoria_id: 5,
                categoria_nombre: 'Vitaminas',
                status: 'Inactivo',
                con_lote: true,
                url_imagen: '',
                con_impuestos: true,
                precio_publico: '49.00',
                volumen_unidad: 'ml',
                volumen_valor: 0,
                peso_unidad: 'mg',
                peso_valor: 1000,
                unidad_entrada: 'Caja',
                unidad_salida: 'Tableta',
                control_almacen: true,
                factor_unidades: 20,
                costo_compra: '31.00',
                numero_registro_sanitario: 'RS-2026-006',
                temperatura: 'Ambiente',
                presentacion: 'Caja con 20 tabletas',
                fecha_entrada: '2026-06-20',
                tags: 'defensas, vitamina',
                objeto_impuesto_id: 1,
                tasa_cuota_id: 1,
                clave_prod_serv_id: '51191601',
                usuario_creacion: 'Sistema',
                usuario_actualizacion: 'Sistema',
                fecha_creacion: '2026-06-20 13:35',
                fecha_actualizacion: '2026-06-20 13:35',
              },
            ],
            total: 6,
            page: 1,
            pageSize: 5,
          });
        }, 300);
      });
    } catch (error) {
      console.error('Error obteniendo productos:', error);
      throw error;
    }
  },
};
